### ISSUE TITLE
Is there an arduino version?

### ISSUE THREAD

**Issue by parallaxengineering** [Tiggilyboo/vanny-hub#3]
Hey, I see you have interface DCC50S with Python, do you happen to have arduino code for same interfacing?

**Comment by Tiggilyboo** [comment]
Hey, thanks for the interest!

I wrote this for interfacing with the RP2040 (most commonly found on the raspberry pi pico) using a library to abstract the modbus protocol - but the concept should still hold true on any microcontroller. So you could find a similar library and call the same modbus functions using the provided addresses from this project if you like?

EDIT: I saw you mentioned python? This is entirely written in C...

**Comment by tbjers** [comment]
@Tiggilyboo maybe close this issue?
